# Schlüsselbegriffe

## Diskriminierung in Daten und Datensätzen

## Forschungsdaten
Forschungsdaten sind Ressourcen, die Forschende während ihrer Forschung verwenden und produzieren. Dazu gehören Datensätze, Software, Quellcode, Workflows, Modelle, Zeitreihen, Tabellen, Bilder, Videos, Interviews und Artikel etc.

Bei der Stadt.Geschichte.Basel und den meisten anderen historischen Forschungsprojekten handelt es sich vor allem um Textdaten, Bilddaten, Tabellen (statistische Zeitreihen etc.), georeferenziertes Kartenmaterial und bibliographische Angaben (Verweise auf Sekundärliteratur). Ein grosser Teil dieser Forschungsdaten stammt aus den Beständen von Gedächtnisinstitutionen wie Archiven, Bibliotheken und Museen oder steht in Form publizierter Ergebnisse (Bücher, Artikel etc.) zur Verfügung. In vielen Fällen sorgen diese Einrichtungen für die Langzeitarchivierung der Ressourcen. Dann kann über die DOI oder die Signatur direkt auf die Ressourcen verwiesen werden. In diesen Fällen sollten alle Informationen erfasst werden, die über die bereits in den Gedächtnisinstitutionen vorhandenen Metadaten hinausgehen. Dabei kann es sich um Quellenannotationen, erweiterte Beschreibungen, korrigierte Angaben etc. handeln. Es empfiehlt sich jedoch auch in diesen Fällen, einen möglichst kompletten Metadatensatz zu erstellen. Redundanz ist bei Forschungsdaten wünschenswert. Es erhöht die Verfügbarkeit und die Auffindbarkeit.

Es gibt aber auch Daten, die im Rahmen der Forschung erzeugt werden. Dazu gehören neben Textdaten (Forschungsprotokollen), statistische Zeitreihen, die aus historischen Quellen zusammengestellt und als Diagramm dargestellt werden, auch Karten und Netzwerkdarstellungen, die aus Grabungsdaten oder anderen raumbezogenen Daten erstellt werden. Diese Daten müssen so gesichert werden, dass sie reproduzierbar sind. Viele textuelle Forschungsdaten liegen nur auf Papier oder in unstrukturierter Form digital vor. Die Extraktion strukturierter Daten aus diesen Materialien erfordert einen hohen Aufwand - Scannen, Bereinigen, Annotieren usw.

Neben den Forschungsdaten müssen auch die dazugehörigen Prozessinformationen und unterstützenden Daten, wie Software, Algorithmen und Protokolle, archiviert und zugänglich gemacht werden. Diese Informationen sind unerlässlich, um die Nachvollziehbarkeit und Reproduzierbarkeit der Forschungsergebnisse zu gewährleisten.

## Metadaten

### Was sind Metadaten?

- Beispiele und Abgrenzung zu *Daten* und *Paradaten*.
- Was ist ein Metadatenobjekt?
- Was ist ein zugeordnete Ressource?
- Können verschieden zueinander im Verhältnis stehen -- in beiden Fällen kann es zu Diskriminierung/Bias kommen.

### Verhältnis von Metadatenobjekten und zugeordneten Ressourcen

#### Ein Metadatenobjekt mit einer zugeordneten Ressource

#### Ein Metadatenobjekt mit drei zugeordneten Ressourcen (Triptychon)

#### Ein Metadatenobjekt mit drei verschiedenen zugeordneten Ressourcen

#### Zwei Metadatenobjekte mit derselben zugeordneten Ressource

### Standards

- Festhalten: Es existieren verschiedene Standards... Fokus hier (vorerst) auf Dublin Core

#### Schemas / Strukturstandard

- Dublin Core Metadata Element Set

::: {.callout-tip title="Tipp der Stadt.Geschichte.Basel"}
Verweis auf Anhang mit Tabellen der Metadaten der Stadt.Geschichte.Basel
:::

#### Formatstandard

- XML/RDF

#### Inhaltsstandard

- Welche Felder wie befüllt werden (z. B. Reihenfolge Vor- und Nachnamen)
- RSWK

#### Wertstandard

- Inhalt der Felder (z. B. GND)

## Opendata-Prinzipien

### Open Data und Langzeitarchivierung

- Grundsätzliches
- Zenodo und andere Aggregatoren und Publikationsorte

### FAIR-Prinzipien

- FAIR ≠ open (in gewissen Kontexten kann Einschränkung sinnvoll sein und ist in FAIR eingeschlossen!)
- ...

### CARE-Prinzipien

- Die CARE-Prinzipien wurde innerhlab www.rd-alliance.org gegründet.
  - C:
  - A:
  - R:
  - E:
- Stand Umsetzung aktuell
  - Noch relativ neu und kommen deshalb erst nach und nach in Umsetzung.
  - Ihre hohe Anziehungskraft (gerade als Komplement zu den FAIR-Prinzipien) verweist jedoch auf ein grosses Bedürfnis.
- Fokus:
  - CARE-Prinzipien adressieren dezidiert indigene Daten, bietet jedoch keinen allgemeinen Rahmen für ethischen Fragen in Bezug auf Sammlungsdaten.
  - Entsprechend stellt sich die Frage, inwieweit die CARE-Prinzipien "fliessend" auf andere Kontexte ausgeweitet werden können, oder ob die Formulierung separater Prinzipien je nach Kontext sinnvoller wäre.
  - Die CARE-Prinzipien liefern wichtige Impulse für FDM um ethische Fragen im Umgang mit Forschungsdaten und -materialien zu reflektieren und systematisch zu berücksichtigen.
  
  #### Communities
  - Bei der konkreten Umsetzung stellen sich Fragen wie: "Wer sind genau die *Communities*?" oder "Wie genau bemessen wir *collective benefit*?" Je nach Kontext sind diese Fragen schwer zu beantworten.
    - Kritische Einordnung des oftmals pauschalisierend eingesetzten Community-Begriffs (vgl. z.B. Kaiser et al. 2023)
    - Verliert eine Gruppe irgendwann die Rechte über ihre Vorfahren? Wer bestimmt, woran festmachen?
    - ...
  - Beispiele nennen für andere Kontexte, e.g. Datenschutzthematik, NS-Register, heterogene Community, ... 
  - TK-Labels (Fokussieren auf Selbstbestimmung bei der Label-Vergabe im Kontext von Institutions-Gatekeeping)


  #### Diskriminierungsfrei vs. Diskriminierungssensibel
  - "Diskriminierungsfrei" im alten Titel aufgreifen
    - Mit dieser Differenzierung soll kein Relativismus betrieben werden!
      - Streben hin zu Diskriminierungsfreiheit: ja, unbedingt; Diskriminierungsfreiheit behaupten: nein
    - Begründung
      - Diskriminierungsverständnis ist geografisch und communityabhängig heterogen 
      - Diskriminierungsverständnis ändert sich -- auch in Zukunft
      - Auch "Normdaten" verändern sich (auch die GND)
      - Dekolonialisierung nie abgeschlossen
      - Archiv-Lücken betonen
      - Archiv-Geschichte bleibt
      - Weit mehr als bloss Vokabular